export default [
    'aby-usd',
    'adcn-usd',
    'adx-usd',
    'apc-usd',
    'aur-usd',
    'bci-usd',
    'benji-usd',
    'bpok-usd',
    'btc-usd',
    'btcd-usd',
    // 'cann-usd',
    // 'cash-usd',
    // 'ch-usd',
    // 'eth-usd',
    // 'fct-usd',
    // 'ftc-usd',
    // 'grc-usd',
    // 'html5-usd',
    // 'liza-usd',
    // 'ltc-usd',
    // 'man-usd',
    // 'met-usd',
    // 'neo-usd',
    // 'nvc-usd',
    // 'rep-usd',
    // 'stx-usd',
    // 'unit-usd',
    // 'ven-usd',
    // 'via-usd',
    // 'vtc-usd',
    // 'zec-usd',
    // '2015-usd',
    // '1st-usd',
    // '1337-usd',
]